name: SwagLabs
on: [push, pull_request]
jobs:
  centros-ui-tests:
    runs-on: ubuntu-latest
    name: Running e2e tests

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

       

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
        

      - name: Install dependencies
        run: npm install
        
        

      - name: Run tests
        run: npm test
       


