name: SwagLabs
on: [push, pull_request, workflow_dispatch]
jobs:
  centros-ui-tests:
    runs-on: ubuntu-latest
    name: Running e2e tests
    timeout-minutes: 5
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
   

      - name: Run docker
        run: npm run docker-build

      - name: run test
        run: npm run docker-all-tests

       
      - name: clear docker
        run: docker compose down --remove-orphans

    
