name: SwagLabs
on:
  workflow_dispatch:
    inputs:
      centrosTarget:
        required: true
        default: https://www.saucedemo.com/
        type: string

jobs:
  centros-ui-tests:
    runs-on: ubuntu-latest
    name: Running e2e tests

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        continue-on-error: true
        run: npm install
        

      - name: Run  e2e tests
        run: npm run test
        continue-on-error: true
        

      - name: Sleep for 15 seconds
        run: sleep 15s
        shell: bash



